CONABIO/enciclovida

- app/helpers/especies_helper.rb
- app/views/especies/filtros.html.erb
- config/locales/es-cientifico.yml
- config/locales/es.yml
> Sql server

- app/views/especies/index.html.erb
- tools/README
Se agregaron las búsquedas comunes y correciones al README
> Cambios al index

- app/helpers/especies_helper.rb
pendientes algunos cambios (dudas)
> taxones subrayados BIS

- app/assets/stylesheets/soulmate.scss
- app/views/especies/filtros.html.erb
> Arreglos definitivos al soulmate

- app/assets/stylesheets/especies.css.scss
- app/views/especies/_arbol.html.erb
- app/views/especies/filtros.html.erb
- app/views/especies/index.html.erb
Básicamente los títulos de los commits
> Cambios de estilo y efectos

- app/controllers/especies_controller.rb
- app/helpers/especies_helper.rb
- app/views/especies/show.html.erb
- app/views/layouts/application.html.erb
- app/views/usuarios/_filtros_vista_basica_busqueda_avanzada.html.erb
- config/locales/es.yml
> Cambios de ultimo momento before PP

- app/assets/stylesheets/carrusel.css
- app/views/especies/resultados.html.erb
- app/views/layouts/application.html.erb
> cambios al scroll del carrusel, arreglo de resultados e icono de sidebar

- app/assets/javascripts/mapas_dinamicos.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/dashboard.css
- app/views/especies/_fotos_carrusel.html.erb
- app/views/especies/resultados.html.erb
- app/views/especies/show.html.erb
bueno sí son conocidos pero  muy específicos para ponerlos aquí, en su lugar, hagamos lo que a torvalds le fascina
> cambios desconocidos despues de la junta,

- app/views/layouts/application.html.erb
> cambio imprevisto

- app/assets/javascripts/general.js
- app/assets/stylesheets/dashboard.css
- app/views/especies/show.html.erb
> envia comentarios

- app/assets/stylesheets/carrusel.css
- app/views/especies/_fotos_carrusel.html.erb
- app/views/especies/show.html.erb
"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae …
> fixes foto carrusel

- app/assets/javascripts/general.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/carrusel.css
- app/assets/stylesheets/dashboard.css
- app/views/especies/show.html.erb
- app/views/layouts/application.html.erb
para quitar comentarios en los css
> esperando q no se descomponga

- app/controllers/validaciones_controller.rb
- app/models/validacion.rb
De seguro me vana decir que cambie shalalalala pero que sí, que no, que el color, no fue el que te pase, que si chunita, chachita, la bolsa, etc, etc, etc.
Sin embargo después de mucho pelear, considero quedo mejor a como se tiene actualmente.
Quedo a la espera de quejas sugerencias y comentarios
Cambio y fuera
> yeeeei finalmente bootstrap con la nueva paleta

- app/controllers/busquedas_controller.rb
- app/views/busquedas/_busqueda_avanzada_vista_avanzada.html.erb
- app/views/busquedas/_busqueda_avanzada_vista_basica.html.erb
- app/views/especies/index.html.erb
> prioritarias desAjustes calonso!!!

- app/assets/javascripts/general.js
- app/views/especies/_panelCaracteristicaDistribucionAmbiente.html.erb
- app/views/especies/index.html.erb
- app/views/inicio/_advertencias.html.erb
- app/views/inicio/_dosVistas.html.erb
- app/views/inicio/_queEs.html.erb
- app/views/inicio/_usos.html.erb
- app/views/layouts/application.html.erb
> BIOS => Biotas

- app/assets/javascripts/general.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/especies.css.scss
- app/helpers/busquedas_helper.rb
- app/helpers/especies_helper.rb
- app/views/busquedas/_busqueda_avanzada_vista_basica.html.erb
- app/views/busquedas/avanzada.html.erb
- app/views/busquedas/basica.html.erb
- app/views/especies/_panelCaracteristicaDistribucionAmbiente.html.erb
- app/views/especies/show.html.erb
- app/views/layouts/application.html.erb
Aún faltan algunos cambios descritos en su correo OJO
> Cambios a peticion de CG 1 de n

- levantaBlurrily.rb
- levantaServerDevelopment.sh
> modificación script para alzar blurrily en un solo paso

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/especies.scss
- app/views/especies/_panelCaracteristicaDistribucionAmbiente.html.erb
- app/views/especies/show.html.erb
- app/views/inicio/acerca.html.erb
> cambios looney toons

- app/assets/javascripts/geodatos/geodatos.js
- app/views/especies/_geodatos.html.erb
* Revisa si con el JS comentado no rompí algo
* El bug del mapa al ser redimensionado ha sido resuelto
* Falta el botón/control  para mapa a pantalla completa
* Necesito las coordenadas del cuadrado de la república para que el zoom se adapte al tamaño de la ventana (leaflet ofrece dicho método)
* Falta que borre los archivos JS (y el código) q no se usa, espero vuestro VoBo.
* Quizá entre hoy y mañana (o en algún momento) cambie a la gema, para reducir los requests de los assets, lo pensare
* Actualice leafleat a la versión 0.7.7 (igual, del cdn)
* Agregue el mapa q te gusta (y a CG [Hybrid])
* Como ya está quedando, hay q borrar google maps del index y sustituirlo por leafleat :P
...ya me voy, ciao
> responsividad mapa parte 2

- app/assets/javascripts/geodatos/geodatos.js
- app/views/especies/_geodata_e_imagen.html.erb
- app/views/especies/_geodatos.html.erb
Falta lo q me decías ayer del mapa de distribución
> Limpieza y merge con el tuyo, 

- app/controllers/comentarios_controller.rb
- app/models/comentario.rb
- app/views/comentarios/_form.html.erb
> Experimental

- app/assets/stylesheets/comentarios.scss
- app/controllers/comentarios_controller.rb
ya se guarda la historia en los correos, falta cachar las respuestas al momento de guardar en la bd (y se reciban de xolo)
lo medito con la lamohada
saludos
> comentarios generales

- app/assets/stylesheets/comentarios.scss
- app/controllers/comentarios_controller.rb
- app/models/usuario.rb
- app/views/comentarios/_admin.html.erb
- app/views/comentarios/_form_respuesta.html.erb
- app/views/comentarios/_historial.html.erb
- app/views/comentarios/admin.html.erb
- app/views/comentarios/show.html.erb
burbujitas en los historiales, falta darle un buen formato al correo y así, ya casi queda :D
> cambios en Comentarios

- app/assets/javascripts/comentarios.js
- app/assets/stylesheets/comentarios.scss
- app/views/comentarios/_admin.html.erb
- app/views/comentarios/admin.html.erb
Falta terminar algunos estilos, pero ya se donde moverle a los tooltips, popover etc
> poniendo cuquis la tablita

- app/assets/stylesheets/comentarios.scss
- app/controllers/comentarios_controller.rb
- app/models/categoria_comentario.rb
- app/views/comentarios/_form.html.erb
- app/views/comentarios/_form_respuesta.html.erb
- app/views/comentarios/_historial.html.erb
- app/views/comentarios/show.html.erb
- app/views/shared/_footer_legal.html.erb
- config/routes.rb
quizá echale un ojo al modelo CategoriasComentario, no debería haber problema, quedo igual con un ifsote
> inicio cambios a petición de cg del 1509216

- app/controllers/adicionales_controller.rb
- app/controllers/application_controller.rb
- app/controllers/comentarios_controller.rb
- app/controllers/especies_controller.rb
- app/controllers/usuarios_especie_controller.rb
- app/helpers/usuarios_especie_helper.rb
- app/models/rol.rb
- app/models/usuario.rb
- app/models/usuario_especie.rb
- app/models/usuario_rol.rb
- app/views/layouts/application.html.erb
- app/views/usuarios/index.html.erb
- app/views/usuarios_especie/_form.html.erb
- app/views/usuarios_especie/edit.html.erb
- app/views/usuarios_especie/index.html.erb
- app/views/usuarios_especie/new.html.erb
- app/views/usuarios_especie/show.html.erb
- config/routes.rb
- db/migrate/20161027003250_add_ancestry_to_roles.rb
- db/migrate/20161027011840_truncate_and_populate_roles.rb
- db/migrate/20161027074449_create_usuarios_especie.rb
- db/schema.rb
- test/controllers/usuarios_especie_controller_test.rb
- test/helpers/usuarios_especie_helper_test.rb
- test/models/usuario_especie_test.rb
relacionadas al viejo rol convirtiendolo en usuario_rol, etc
OJO, correr los seed en produccion
> Arreglos para que funcione con todas las nuevas migraciones

- app/controllers/comentarios_controller.rb
- app/models/usuario.rb
- app/models/usuario_especie.rb
Also, los dos dejamos más limpia la accion admin, movimos lo mismo, genial coordinación ¬¬  !>.>
Falta filtrar por categoria y listo
De mientras ya no vi bugs (se puede poner en prod)
Also echale un ojo al merge, yo doy mi VoBo. da el tuyo
> Ya se filtra por especie en los comentarios de acuerdo al usuario

- app/views/usuarios/show.html.erb
> bug q tronaba cuando el usuario no tiene roles o catsCons o taxa

- app/views/shared/_brandBar.html.erb
> Cambiando liga de logotipo conabio

- app/helpers/busquedas_helper.rb
- app/models/especie.rb
> parche estatus 9 y 6

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/busquedas.css
- app/views/busquedas/__resultados.html.erb
> resultados atractivos

- lib/iucn_service.rb
esta abajo de lib, muy sencillito
> servicio de IUCN

- app/views/inicio/_index_especies_destacadas_video.html.erb
Actualización a las fotos de las especies destacadas
> especies destacadas update

- app/assets/stylesheets/inicio.scss
- app/views/inicio/_index_intro_video.html.erb
- lib/github_service.rb
tanto visuales como en backend
> ajustes seccion de news

- app/views/especies/show.html.erb
En el correo pondré la justificación visual ¬¬
En cuanto al PDF, hay q  volver a reescribirlo ya que estaba íntimamente ligado a Photos(modelo) y pues salieron varios errores (no sale hoy)
> Cambios petición CG

- app/views/ubicaciones/_especies.html.erb
- app/views/ubicaciones/_grupos.html.erb
- app/views/ubicaciones/_tipos_regiones.html.erb
- app/views/ubicaciones/por_region.html.erb
solamente se pone presentable para el lunes...
considero que falta un maquetaje apropiado, sin emabrgo solamente se utilizaron las clases y estilos de los resultados
> Poniendo medio coqueto la búsqueda por región

- app/controllers/especies_controller.rb
- app/views/especies/show.html.erb
- config/routes.rb
- lib/bdi_service.rb
Incluye interfaz para el cambio de id de naturalista (cambio en tabla proveedor)
Incluye parche FEO para que se vean las fotos del BDI los romeritos en enciclovida
OJO, hay q revisar el servicio en los queries de consulta
Se creo esta rama debido a que mi rama principal (sql-server) YA estaba mezclada con la rama explora_por de @calonso-conabio 
Saludos!!
> Cambios para CG 

- app/assets/javascripts/geodatos/ubicaciones/por_region.js
- app/assets/javascripts/geodatos/ubicaciones/por_region_delayed.js
- app/assets/stylesheets/geodatos/ubicaciones/por_region.css
- app/views/inicio/index.html.erb
- app/views/shared/_brandBar.html.erb
- app/views/ubicaciones/_tipos_regiones.html.erb
- app/views/ubicaciones/por_region.html.erb
visualizacion orden y textos en explora_por
> cambios peticion CG

- app/models/proveedor.rb
- lib/cache_services.rb
@calonso-conabio  revisa el commit:
https://github.com/calonso-conabio/buscador/commit/ca479da72d5cb69d51881e335009ad448af40f0a
cache, parchado
> Centralizacion

- app/assets/javascripts/peces/peces_extra.js
- app/assets/stylesheets/peces/peces_extra.scss
- app/controllers/pmc/peces_controller.rb
- app/helpers/peces_helper.rb
- app/views/layouts/peces.html.erb
- app/views/pmc/peces/_mini_show.html.erb
> cambios peces

- app/assets/stylesheets/peces/peces_extra.scss
- app/helpers/peces_helper.rb
- app/views/pmc/peces/_mini_show.html.erb
- app/views/pmc/peces/resultados.html.erb
cambios eternos, en un solo commit u.u #myBad
> añadiendo filtros usados en la busqueda a los resultados

- app/controllers/especies_controller.rb
- app/lib/taxon_describers/wikipedia.rb
- app/lib/taxon_describers/wikipedia_es.rb
- app/lib/web_services/wikipedia_service.rb
- config/initializers/string.rb
- config/routes.rb
Tiene los cambios para poder consumir el resumen de wikipedia en inglés o español
> Alternativo

- app/assets/stylesheets/especies.scss
- app/assets/stylesheets/general.scss
- app/views/especies/show.html.erb
en nombre científico
tamaño de iconos
> cambios sugeridos por el cristoforo

- app/controllers/pmc/peces_controller.rb
https://www.youtube.com/watch?v=sXhvCtqmhBs
> nirvana - i hate myself and want to die

- app/helpers/busquedas_helper.rb
- app/models/catalogos/catalogo.rb
- app/models/catalogos/especie.rb
- app/models/lista.rb
- app/views/busquedas_regiones/especies.html.erb
- config/locales/es.yml
Se hizo mas ágil la descarga combinando sentencias includes
Se incluyo Usos y Agrobiodiversidad en la descarga
Se incluyeron campos default como nombre común principal y foto principal
> Descarga en búsqueda avanzada y por región

- public/topojson/anp.geojson:Zone.Identifier
- public/topojson/estado.geojson:Zone.Identifier
- public/topojson/municipio.geojson:Zone.Identifier
Se agregaron nuevos archivos de topojson y se realizo el cambio a la base de datos a ahora es geoportal2025
> cambio de base de datos completados , nuevos archivos en topojason

- .byebug_history
- Gemfile
- Gemfile.lock
- app/assets/javascripts/update_maps.coffee
- app/assets/stylesheets/update_maps.scss
- app/controllers/admin/update_maps_controller.rb
- app/helpers/update_maps_helper.rb
- app/models/catalogos/especie.rb
- app/models/catalogos/taxon_naturalista_client.rb
- app/views/admin/update_maps/upload.html.erb
- app/views/shared_b4/_dropdown_menu.html.erb
- config/routes.rb
- test/controllers/update_maps_controller_test.rb
Se creo un modulo para actualizar los mapas de las especies ,esto para automatizar el proceso que se realizaba manualmente.
> Modulo para actualizar mapas

- app/views/especies/_geodata.erb
se agrego un nuevo link de descarga en formato csv para las especies
> nuevo link para descargar de csv

- app/assets/javascripts/comentarios/comentarios_extra.js
- app/controllers/comentarios_controller.rb
- app/models/comentarios/comentario.rb
- app/views/comentarios/_historial.html.erb
- app/views/layouts/admin.erb
- app/views/layouts/application.html.erb
- app/views/layouts/application_b3.html.erb
- app/views/layouts/busquedas_regiones.html.erb
- app/views/layouts/descripcion_app.html.erb
- app/views/layouts/especies.erb
- app/views/layouts/estadisticas.html.erb
- app/views/layouts/fichas.html.erb
se arreglo el js para enviar las respuestas a los comentarios
> respoonder comentarios solucionado
